service: api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

  stage: dev
  region: us-east-1



functions:
  register:
    environment:
      DYNAMODB_USERS_TABLE: ${ssm:dev-parameter-users-register-table_name}
    handler: register/handler.register
    role:  ${ssm:dev-parameter-users-register-register-role-arn} 
    events:
      - httpApi:
          path: /users
          method: post

  login:
    environment:
      DYNAMODB_USERS_TABLE: ${ssm:dev-parameter-users-register-table_name}
      JWT_SECRET: ${ssm:dev-parameter-jwt-secret}
      EMAIL_GSI: ${ssm:dev-parameter-users-register-gsi_email}
    handler: login/handler.login
    role:  ${ssm:dev-parameter-users-login-login-role-arn} 
    events:
      - httpApi:
          path: /login
          method: post

custom:
  stage: ${opt:stage, self:provider.stage}
